### ISSUE TITLE
http://implicitcad.org/ is down

### ISSUE THREAD

**Issue by l29ah** [colah/ImplicitCAD#215]

**Comment by julialongtin** [comment]
My apologies, my hosting site was recently hit with two days of bouncing
power, and the site has been unstable since then.
I'm trying to hunt down the problem, but until then, if you spot it not
working, and want it working, reply to this thread, OR if you're in the US,
call or text message me at 479-966-9254.  it takes me about 5 minutes to
restart it... but i still haven't established root cause for why the site
is dieing.

**Comment by micrenda** [comment]
Hello,

It seems the main project page is again down.

Thank you for your help on keeping this project alive :-)

Best regards
Michele

**Comment by julialongtin** [comment]
on it.

**Comment by julialongtin** [comment]
fixed. thank you for the report!

**Comment by l29ah** [comment]
503

**Comment by julialongtin** [comment]
fixed. server randomly powered itsself off last night.
