### ISSUE TITLE
DXF Import Not Working

### ISSUE THREAD

**Issue by andrewjbarton** [colah/ImplicitCAD#55]
I was able to get basic linear_extrude example working, but as soon as I attempt to import a DXF file for extrusion I run into problems. I tried two approaches.
1.  linear_extrude(file = "path.dxf", height = 20);
   result: 
   At line 7:Module linear_extrude gave the following warnings:  unused arguments
   Nothing to render 
2. linear_extrude(height = 20) import("path.dxf");
   At line 7:module import is not in scope

Perhaps dxf import is not supported at this time. Is any other import format supported?

**Comment by wbrickner** [comment]
I'm not good with Haskell - I'm a beginner.
I'm learning however.
Question:
What data really needs to be parsed from DXF or other formats?
Like, what data do you need to end up with in order to work with it inside ImplicitCAD?
I'd be interested in writing or collaborating on a library/class (or whatever) that was able to parse any given file format based on an installable extension. I hope what I'm saying is clear enough.
I'm imagining a parser that is modular. You would write a file which can be loaded by the library, which expresses how to convert some given file format into the one used by ImplicitCAD. That way there is no reason to hard code it, and the community can write the conversion modules instead of waiting, and hoping for a release that happens to support their filetype.

Please, let me know if you're interested in a collaboration!

**Comment by julialongtin** [comment]
for the foreseeable future, we are not supporting importing from other formats.
